# Generated by Django 4.1 on 2022-08-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='default title', max_length=20)),
                ('short_description', models.TextField(default='default description')),
                ('image', models.FilePathField(default='default', path='/img')),
            ],
        ),
    ]
