# Generated by Django 4.1 on 2022-08-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.CharField(blank=True, max_length=150, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.TextField(default='default description', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technology',
            field=models.CharField(blank=True, max_length=20, verbose_name='Технологии'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default='default title', max_length=20, verbose_name='Заголовок'),
        ),
    ]
